language: node_js
node_js: stable
sudo: required
addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
script:
- npm test
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then npm run test:sl; fi
env:
  global:
  - secure: kZjWrzHka+4Ue3QGdhuQ9V4IT/3DiHdH2u/DIwKUfalDZp3QFs9SpPeGFjAvOAfU1XG1legiWjh3suFCWrLFFvwQz/j+Ir7QQEbU/3k4tpaE3uPwuqzS38ZFR+IL8Az9O6TWThuDn/ejHlmHp58MNdtDaBnZMcdL4vcmSneb/U4/seKM0DL3wRxYBdBx8/tjaOpGptQJxTM7TIJmLQdktFFSCju8v3fLSc+JhKPhX3sbAT4PDULn0YgU5dft6yqdVXVldec5yke3pWIbEGJCsUD+DBTnCDR+hCPJEddLF0dEguHZ2EwfLJfPDwGdrZIK+Ghwo7RwiirdGuk1fYR1FPAZt4f2//e7ydqiJAicEwDIYbucwUoAc3PIo8jMG6/ZhuVB8WGipA2ZkUST6zN+Hqfh3sK/maInMOUEBlDv8HGG5F7qgyYHOZ1TCfg5hWCG6WJ+TCnQEiBSXhxjJGsIeILUHKDVJDNW/sTNUEXEiLWNLvyeguBH1L6d5BqqBX3gUsK5dGcJMCx2EtoNSzmj4pUJAfkTzDeCNids9v9Xwcc5rhiozf9FFwxzu0qZ4n75zkR0d330i0kO9w6dQ6PQboWljUbhZa8h1nqTeZxJrdGTVRgMD9cJEvsB2VmzJCzHRqLh0fvF+qM/E8u4WZpyr9sYSzv31qPsIvrhe/X1iMA=
  - secure: A087Sm+c5r+Sjc5YgyW8LHC1EzEH/cqp/1J+ieUw/f8tlNAnwRjHe0MBWac3ejXnom88DdAQNV76Tf7YRyuPPgBPGAGq4QrRQVYxdUXnlL0ilHy9tNEKRqh6vnGeHe0kVe5cPDnPEzj6Wk//3EiQ3z1iMhvL4a/tIH8/wGDXX2axEhkgxujtLuS7oKYSyDiZk5Hf1qRtiujQu5H94qED1g4LWNskZ09O2Q/HHRpwTTUsd8HHqd9eaWlgLROfiiUxDR/ZLAykrJqH53uLgMRCru5bmsF8FpUpDtY2abLcaxgS8Mf24S6ZIJGsDogh4R0w9rHlHu5jxPdY7jPASbzEZ7a4GZawwEZBE8Vd2dw4ci+5rlS81oK5YnQc04toARRhIzP1oT0r1QSiz/uL/EOF3tC4qYeqQcsnx0KKeKgwH/KLahkI0ukBjlslFAXGzyiz0sUU1SBBs5ksoP5Zg6ZPwkkgkgrdSq5L8vfluSd9o16P+If6P2xj+Amw3+OdkJkaybcpW1rLnl+xQ9zTyolaza/6uM2bxOeRfhCEP+ILqvZrCVTKODjTfV6+HT+V3e5HJqrm20EFW5qcIiOTa7Bv+ZFJUuoKGxvj2kMw9s3o7QyXscOdtgNCB6Txvi5Q1eFrx240o5q9rq8aAgmLZ39tAQRK9y765k04b9xEiPaM6gg=
